name: Engine Stressor - Install and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 * * *' # This sets the workflow to run daily at 3AM

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make containernetworking-plugins

      - name: Run make install
        run: sudo make install

      - name: Pull Docker image
        run: docker pull quay.io/centos-sig-automotive/automotive-osbuild

      - name: Run engine stressor
        run: |
          sudo TOTAL_MEMORY_FOR_THE_NAMESPACE="1G" \
            LIST_CURRENT_STATE=true \
            VERBOSE=true \
            CLEANUP=true \
            TIMEOUT_PODMAN_STOP_CONTAINER=5 \
            NETWORK_NAME="my-network" \
            VOLUME_NAME="my-volume" \
            IMAGE_NAME_CONTAINER="quay.io/centos-sig-automotive/automotive-osbuild" \
            IMAGE_COMMAND="sleep 3600" \
            NUMBER_OF_CONTAINERS="100" \
            ./engine-stressor

      - name: Run engine stressor WITH NETWORK + DNS_SERVER + VOLUME
        run: |
          sudo TOTAL_MEMORY_FOR_THE_NAMESPACE="1G" \
            LIST_CURRENT_STATE=true \
            VERBOSE=true \
            CLEANUP=true \
            TIMEOUT_PODMAN_STOP_CONTAINER=5 \
            NETWORK_NAME="my-network" \
            NETWORK_DNS_SERVER="8.8.8.8" \
            VOLUME_NAME="my-volume" \
            IMAGE_NAME_CONTAINER="quay.io/centos-sig-automotive/automotive-osbuild" \
            IMAGE_COMMAND="sleep 3600" \
            NUMBER_OF_CONTAINERS="100" \
            ./engine-stressor

      - name: Run engine stressor WITH NETWORK + DNS_SERVER + VOLUME + STRESS
        run: |
          sudo TOTAL_MEMORY_FOR_THE_NAMESPACE="1G" \
            LIST_CURRENT_STATE=true \
            VERBOSE=true \
            STRESS_CPU="6" \
            STRESS_DISK="8" \
            STRESS_DISK_SIZE="1G" \
            STRESS_MEMORY="1G" \
            STRESS_VM_STRESSOR_INSTANCES=100 \
            STRESS_TIME="60s" \
            CLEANUP=true \
            TIMEOUT_PODMAN_STOP_CONTAINER=5 \
            NETWORK_NAME="my-network" \
            NETWORK_DNS_SERVER="8.8.8.8" \
            VOLUME_NAME="my-volume" \
            IMAGE_NAME_CONTAINER="quay.io/centos-sig-automotive/automotive-osbuild" \
            IMAGE_COMMAND="sleep 3600" \
            NUMBER_OF_CONTAINERS="100" \
            ./engine-stressor
