name: Beakerlib - Install and run Engine Stressor

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull Fedora container
        run: docker pull fedora:latest

      - name: Run tests in Fedora container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace fedora:latest /bin/bash -c "
          dnf install -y podman make git beakerlib;
          make;
          make install;
          cd tests/beakerlib/N-instances-podman-parallel;
          ./runtest.sh"
